#!/usr/bin/env node
// collect-staging.mjs — snapshot cac nhanh staging/writer-K (READ-ONLY).
// Chay trong coordinator (production.yml) SAU khi da git fetch origin.
// Voi moi writer-K: doc sha cua refs/remotes/origin/staging/writer-K va
// liet ke file bai moi (added) / sua (repaired) so voi origin/main, chi _posts/*.md.
// Dung diff HAI-CHAM (origin/main..sha = so sanh NOI DUNG voi main tip):
//   - file giong het main (con lai tu lich su fork merge-base cu) KHONG dem —
//     bug cu: diff BA-CHAM (origin/main...sha) dem bai da tich hop la
//     'added' khi staging fork tu main cu, lam guard tu choi
//     "day N bai, vuot writer_chunk_size".
//   - added    = file KHONG ton tai tren main (bai moi).
//   - repaired = file CO tren main nhung noi dung khac (sua bai da publish).
// Thong nhat voi apply-staging.mjs (cung hai-cham): collect va apply phai
// thay dung mot tap file.
// Ghi:
//   /tmp/scope.json       — { branches: [{name, sha, added:[], repaired:[]}] }
//   /tmp/reset-staging.sh — script reset staging ve main HEAD sau khi publish,
//                           dung force-with-lease voi sha DA snapshot (khong
//                           bao gio clobber push moi cua writer len nhanh rieng).
// Xuat GITHUB_OUTPUT: noop=true khi khong nhanh nao co bai (idempotent).
import { readFileSync, existsSync, writeFileSync, appendFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = process.env.LAB_ROOT
  ? resolve(process.env.LAB_ROOT)
  : resolve(join(dirname(fileURLToPath(import.meta.url)), '..'));

function die(msg) {
  console.error('::error::' + msg);
  process.exit(1);
}
function git(args) {
  return spawnSync('git', args, { cwd: ROOT, encoding: 'utf8' });
}

let writers = 3;
const cfgPath = join(ROOT, 'data', 'factory-config.json');
if (existsSync(cfgPath)) {
  try {
    const c = JSON.parse(readFileSync(cfgPath, 'utf8'));
    if (Number.isInteger(c.writers) && c.writers > 0) writers = c.writers;
  } catch (e) {
    die('data/factory-config.json khong hop le: ' + e.message);
  }
}

const branches = [];
for (let k = 1; k <= writers; k++) {
  const name = 'staging/writer-' + k;
  const rev = git(['rev-parse', '--verify', 'refs/remotes/origin/' + name]);
  if (rev.status !== 0) continue; // nhanh chua ton tai — khong loi
  const sha = (rev.stdout || '').trim();
  // Contamination guard: a writer branch may differ from main ONLY in _posts/*.md.
  const all = git(['diff', '--name-only', 'origin/main..' + sha]);
  if (all.status !== 0) die('git diff that bai cho ' + name);
  const stray = (all.stdout || '').split('\n').map(s => s.trim()).filter(Boolean).filter(p => !/^_posts\/[a-z0-9-]+\.md$/.test(p));
  if (stray.length) die('staging contamination tren ' + name + ': file ngoai _posts/*.md khac main (' + stray.join(', ') + ') — writer KHONG DUOC sua .github/scripts/data/sitemap; reset nhanh ve main HEAD truoc khi day bai.');
  // Hai-cham: chi file THUC SU khac noi dung main moi tinh la thay doi.
  const changed = git(['diff', '--name-only', 'origin/main..' + sha, '--', '_posts/*.md']);
  if (changed.status !== 0) die('git diff that bai cho ' + name);
  const added = [];
  const repaired = [];
  for (const f of (changed.stdout || '').split('\n').map(s => s.trim()).filter(Boolean)) {
    const onMain = spawnSync('git', ['cat-file', '-e', 'origin/main:' + f], { cwd: ROOT }).status === 0;
    if (onMain) repaired.push(f); else added.push(f);
  }
  if (added.length || repaired.length) branches.push({ name, sha, added, repaired });
}

const noop = branches.length === 0;
writeFileSync('/tmp/scope.json', JSON.stringify({ branches }, null, 2) + '\n');
let sh = '#!/bin/sh\n# generated by collect-staging.mjs — reset staging da snapshot ve main HEAD\nset -eu\n';
for (const b of branches) {
  sh += 'echo "reset ' + b.name + ' (lease ' + b.sha.slice(0, 8) + ')..."\n';
  sh += 'git push --force-with-lease=refs/heads/' + b.name + ':' + b.sha + ' origin HEAD:refs/heads/' + b.name + '\n';
}
writeFileSync('/tmp/reset-staging.sh', sh);
if (process.env.GITHUB_OUTPUT) {
  appendFileSync(process.env.GITHUB_OUTPUT, 'noop=' + (noop ? 'true' : 'false') + '\n');
}
console.log('collect-staging: ' + (noop ? 'khong co bai tren staging — noop.' : branches.map(b => b.name + ' +' + b.added.length + ' moi, ~' + b.repaired.length + ' sua, @' + b.sha.slice(0, 8)).join(' | ')));
